# Default configuration for SD-ITS-Benchmark
# This file contains the base configuration that applies to all environments

[server]
host = "127.0.0.1"
port = 4000
workers = 4
request_timeout = 30
max_request_size = 10485760  # 10MB in bytes
cors_origins = ["http://localhost:4000", "http://localhost:3001"]

[database]
url = "sqlite:./my-database.db"
max_connections = 10
min_connections = 1
idle_timeout = 600
max_lifetime = 1800
connection_timeout = 30

[logging]
level = "info"
format = "text"
output = "console"
file_path = "logs/app.log"
max_file_size = 10485760  # 10MB in bytes
max_files = 5

[application]
name = "SD-ITS-Benchmark"
version = "0.1.0"
environment = "development"
upload_dir = "uploads"
max_upload_size = 52428800  # 50MB in bytes
allowed_file_types = ["json", "txt", "csv"] 